### ISSUE TITLE
does not support mathjax

### ISSUE THREAD

**Issue by SerokSSR** [SukkaW/hexo-lute#2]
it seems that this plugin does not support mathjax(using '$' as symbol), while hexo-renderer-marked does.

$...$ inline formula:

![image](https://user-images.githubusercontent.com/64728373/91539545-14902a00-e94c-11ea-94e7-93b761d43369.png)
![image](https://user-images.githubusercontent.com/64728373/91539611-2c67ae00-e94c-11ea-9bff-3edd9b2a454d.png)

$$ \n $$ formula:

![image](https://user-images.githubusercontent.com/64728373/91539804-7b154800-e94c-11ea-98d1-f2a0abca6365.png)
![image](https://user-images.githubusercontent.com/64728373/91539824-849eb000-e94c-11ea-9ce5-62b24031c469.png)

**Comment by SukkaW** [comment]
Please open a new issue here: https://github.com/88250/lute

**Comment by SerokSSR** [comment]
i see

thanks
